apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: k8s-lab
  labels:
    app: frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: nginx
          image: nginx:1.27-alpine
          ports:
            - containerPort: 80
          volumeMounts:
            - name: html
              mountPath: /usr/share/nginx/html
            - name: nginx-config
              mountPath: /etc/nginx/nginx.conf
              subPath: nginx.conf
              readOnly: true
          livenessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          readinessProbe:
            httpGet:
              path: /health
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5
      volumes:
        - name: html
          configMap:
            name: frontend-config
            items:
              - key: index.html
                path: index.html
        - name: nginx-config
          configMap:
            name: frontend-config
            items:
              - key: nginx.conf
                path: nginx.conf